platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cameloper/Podspec'

use_frameworks!

target 'LogUploader_Example' do
  pod 'LogUploader', :path => '../'
  #pod 'LogUploader'
  target 'LogUploader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
