use_frameworks!

target 'LogUploader_Example' do
  pod 'LogUploader', :path => '../'
  pod 'XCGLogger'
  pod 'Alamofire'

  target 'LogUploader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
